export const goodDeeds = [
  "Informiere dich über den Fairteiler in Baden und oder generell über die Möglichkeiten des Foodsharings",
  "Mach heute jemandem ein ehrlich gemeintes Kompliment! Oder zwei. Oder drei",
  "Koche oder backe heute etwas für jemanden",
  "Lächeln. Kostet nichts. Sorgt bei dir und anderen für gute Laune. Also lächel heute was das Zeug hält!",
  "Schreibe 3 Dinge auf, für die du dankbar bist. Das schafft ein positives Gefühl und lenkt die Aufmerksamkeit auf die schönen Dinge.",
  "Hebe heute einfach mal ein Stück Müll auf, das nicht dir gehört. An sauberen Straßen haben alle Freude!",
  "Unterstütze jemanden aus deiner Familie, der gerade viel zu tun hat. Einfach mal so!",
  "Poste etwas Nettes über 3 Personen oder sende 3 FreundInnen eine Nachricht und sag ihnen, warum du sie magst und was du an ihnen schätzt.",
  "Biete(älteren) NachbarInnen deine Hilfe an, beispielweise, indem du im Stiegenhaus einen Zettel aufhängst auf dem du deine Unterstützung anbietest(zb beim Einkaufen)",
  "Kauf dir eine plastikfreie Trinkflasche. So musst du in Zukunft nicht mehr auf Einwegflaschen zurückgreifen und du vermeidest viel Plastikmüll!",
  "Wusstest du dass es bereits einige Unternehmen gibt die gebrauchte elektronische Geräte generalüberholen und dann wieder verkaufen? Informiere dich über solche Unternehmen - zb. Auf Refurbed.at",
  "Wir alle haben alte FreundInnen, zu denen wir seit Ewigkeiten keinen Kontakt hatten. Denk heute über eine solche Freundin / einen solchen Freund nach und melde dich mal wieder bei ihm oder ihr!",
  "Lieber schenken oder beschenken lassen? Mach jemandem ein kleines Geschenk. Einfach so.",
  "Nimm dir die Zeit jemandem etwas zu erklären Zum Beispiel Technik, die du beherrschst, der / die andere aber nicht.",
  "Miste deinen Kleiderschrank aus und spende die noch(guten) ausgemisteten Sachen",
  "Informiere dich über ein Hilfsprojekt deiner Wahl und überleg was du hier beitragen könntest.",
  "Mach dir Gedanken über Geschenke – Plane zb schon jetzt bewusst ein Weihnachts oder Geburtstagsgeschenk anstatt kurz vorher einfach irgendwas zu kaufen",
  "Höre ernsthaft zu wenn dir jemand etwas erzählen will",
  "Bedanke dich für etwas über dass du dich freust",
  "Beseitige Unordnung die du siehst – Auch wenn du damit gar nichts zu tun hast.",
  "Teile etwas mit jemandem",
  "Gewöhne dir etwas ab, das andere stört",
  "Überrasche jemanden mit etwas Schönem",
  "Verteile schöne Nachrichten an öffentlichen Orten – Schreibe dir ein paar liebe Botschaften auf Post Its und hinterlasse sie an Orten, an denen sie andere Menschen glücklich machen können, wenn sie sie lesen.",
  "Bringe jemanden zum Lächeln",
  "Verschenke etwas das du selbst gemacht hast - einfach so",
  "Spare heute Ressourcen – Wasser, Plastik, Papier... alles was nicht verbraucht oder weg geworfen wird, ist ein Erfolg!",
  "Plane eine Schnitzeljagd oder etwas ähnliches für deine FreundInnen",
  "Hinterlasse einem Freund oder einer Freundin eine süße kleine Nachricht, an einem Ort, wo man sie nicht erwartet!",
  "Bedanke dich bei deinen Eltern",
  "Staubsaug mal die Wohnung / das Haus",
  "Sei freundlich zu jemanden, auch wenn du ihn oder sie nicht besonders gern magst",
  "Mach für deine Freunde eine Playlist mit all euren Lieblingssongs",
  "Schenke einem Freund / einer Freundin ein offenes Ohr bei Problemen",
  "Achte einen Tag bewußt darauf dich nicht zu beschweren. Das stimmt dich selbst positiver und auch deine Mitmenschen.",
  "Versuche heute möglichst wenig zu schimpfen.",
  "Sage einer Lehrerin oder einem Lehrer etwas Nettes.",
  "Versuche jemanden zum Lachen zu bringen.",
  "Versuche, einen Streit zu schlichten.",
  "Schreibe unbemerkt eine nette Botschaft für ein Familienmitglied und lege sie aufs Bett.",
  "Iss heute kein Fleisch",
  "Wasche heute Geschirr ab",
  "Schreibe einen Brief an jemanden",
  "Schicke jemanden eine hübsche Postkarte",
  "Suche ein schönes Foto von dir mit FreundInnen und schicke es ihnen",
  "Räum deinen Bereich im Badezimmer auf",
  "Verschenke etwas das du nicht mehr brauchst",
  "Vergib jemanden auf den du böse bist",
  "Rufe jemanden an / schreibe jemanden und frage ob du etwas für die Person tun kannst",
  "Gib jemanden Nachhilfe / hilf bei Schulaufgaben",
  "Räum etwas weg das schon lange herum steht",
  "Sortiere den Kühlschrank und überleg was du mit den Lebensmitteln machen könntest die bald ablaufen",
  "Versuche heute möglichst ohne Plastik auszukommen",
  "Upcycle etwas",
  "Überleg dir heute zweimal wozu du nein sagst! Vielleicht ist doch etwas dabei das du ausprobieren willst.",
  "Gieße die Pflanzen oder füttere heute die Haustiere",
  "Räum dein Zimmer auf",
  "Achte heute bewusst darauf elektronische Geräte abzuschalten wenn du sie gerade nicht brauchst",
  "Bring heute den Müll raus",
  "Achte heute besonders darauf das Licht auszuschalten sobald du dich nicht im Raum aufhältst"
];
